network:
  pc_ip: "192.168.50.1"
  pc_listen_ip: "0.0.0.0"
  pi_ip: "192.168.50.2"
  pi_listen_ip: "0.0.0.0"

ports:
  rs_udp: 50010
  ppg_tcp: 9999
  audio_udp: 40100

realsense:
  color_w: 640
  color_h: 480
  depth_w: 480
  depth_h: 270
  fps: 15
  mtu_payload: 1400
  no_depth: false
  rs_timeout_ms: 200
  max_inflight: 8

ppg:
  log_dir: "logs/"
  rotate_seconds: 3600
  fsync_every: 0
  rate_print: true
  force_poll: true
  no_data_timeout: 5.0
  poll_sleep_ms: 5.0
  pc_poll_hz: 500.0

audio:
  bt_mac: "28:FA:19:0F:E9:CF"
  pair: true
  trust: true
  bt_reconnect_every: 10.0
  recv_reassembly_timeout_s: 1.0
  keep_audio_files: false
  debug_udp: true
  send_chunk_bytes: 1200
  send_inter_packet_sleep_s: 0.05
  send_sndbuf_bytes: 8388608
  send_repeat_chunk0: 1
  min_inter_file_gap_s: 0.15
  per_label_cooldown_s: 1.2
  volume: 1.0
  output_blocksize: 2048
  output_latency_s: 0.15
  scene:
    window_ms: 1000
    max_objects: 1
  # long-term streaming mode
  stream:
    enabled: false
    port: 50030
    sample_rate: 16000
    channels: 2
    frame_ms: 20
    mtu_payload: 1400
    sndbuf_bytes: 8388608
    jitter_ms: 120
    max_jitter_ms: 400

yolo:
  model: "yolov8n.pt"
  conf: 0.50 # 0.30
  stable_seconds: 0.20
  forget_seconds: 1.00
  cooldown_seconds: 0.60
  yolo_hz: 5.0
  max_det: 4

sonification:
  default_sound: "./sound-lib/ui_sci-fi-sound-36061.wav"
  sofa: "./sofa-lib/BRIR_HATS_3degree_for_glasses.sofa"
  enable_pc_sonifier: false
  out_sr: 16000
  clip_s: 0.35
  fade_ms: 8.0
  max_peak: 0.95 # 0.95
  sound_map:
    person: "./sound-lib/mixkit-retro-game-notification-212.wav"
    couch: "./sound-lib/mixkit-arcade-mechanical-bling-210.wav"
    chair: "./sound-lib/mixkit-arcade-mechanical-bling-210.wav"
    door:  "./sound-lib/mixkit-unlock-game-notification-253.wav"
    object: "./sound-lib/Shortzz.mp3"
